apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservices
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-microservices
  template:
    metadata:
      labels:
        app: immich-microservices
    spec:
      containers:
        - name: microservices
          image: ghcr.io/immich-app/immich-server:v2.5.6
          args: ["start.sh", "microservices"]
          env:
            - name: UPLOAD_LOCATION
              value: /usr/src/app/upload
            - name: LIBRARY_LOCATION
              value: /usr/src/app/library
            - name: IMMICH_PORT
              value: "2283"
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_HOSTNAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_DATABASE_NAME
            - name: REDIS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: REDIS_HOSTNAME
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: uploads
            - mountPath: /usr/src/app/library
              name: library
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: immich-uploads
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
