apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-uploads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 200Gi
