apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopmgr
  namespace: shopmgr
  labels:
    app: shopmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopmgr
  template:
    metadata:
      labels:
        app: shopmgr
    spec:
      containers:
        - name: shopmgr
          image: ghcr.io/tuqui77/shopmgr:0.15.0
          env:
            - name: Jwt__Token
              valueFrom:
                secretKeyRef:
                  name: shopmgr
                  key: Jwt__Token
            - name: ConnectionStrings__ShopMGRDbContexto
              valueFrom:
                secretKeyRef:
                  name: shopmgr
                  key: ConnectionStrings__ShopMGRDbContexto
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app/imagenes
              name: imagenes
      volumes:
        - name: imagenes
          persistentVolumeClaim:
            claimName: shopmgr
