apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - operator/sealed-secret.yaml
  # - operator/crds.yaml
  # - operator/rbac.yaml
  # - operator/deployment.yaml
  # - operator/ingressClass.yaml
  # - connectors/subnet-router.yaml
  # - connectors/sealed-secret.yaml
