apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: lscr.io/linuxserver/mariadb:11.4.8@sha256:d33fb3da7766dbe445f4781b0a78e42fcf7e87d8cb4c9f2d5a37abaa8c4316ca
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: booklore
            - name: TZ
              value: America/Argentina/Buenos_Aires
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booklore
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: booklore
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booklore
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: meriadb-config
