apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-paperless
  labels:
    app: redis-paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-paperless
  template:
    metadata:
      labels:
        app: redis-paperless
    spec:
      containers:
        - name: redis-paperless
          image: docker.io/library/redis:8@sha256:73dad4271642c5966db88db7a7585fae7cf10b685d1e48006f31e0294c29fdd7
          ports:
            - containerPort: 6379
