apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend
  namespace: shopmgr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 10Gi
