apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 5Gi
