apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: dashboard
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: default
    gateway: true
  settings.yaml: |
    background: 
        image: https://images.unsplash.com/photo-1485470733090-0aae1788d5af?q=80&w=1217&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
        blur: lg
        opacity: 70
    cardBlur: xs
    theme: dark
    color: slate
    target: _self
    statusStyle: "dot"
    language: es

    layout:
      Homelab:
        style: row
        columns: 3

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Bookmarks:
        - Github:
            - abbr: GH
              href: https://github.com/Tuqui77
        - Youtube:
            - abbr: YT
              href: https://youtube.com
        - Reddit:
            - abbr: RT
              href: https://reddit.com
        - MercadoLibre:
            - abbr: ML
              href: https://mercadolibre.com.ar
        - MercadoPago:
            - abbr: MP
              href: https://mercadopago.com.ar

  services.yaml: |
    - Homelab:
        - Proxmox:
            icon: proxmox.png
            href: https://192.168.100.155:8006

        - ArgoCD:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/argo-cd.png
            href: https://argocd.tomasmerino.com

        - Qnap:
            icon: qnap.png
            href: http://192.168.100.56:8080


    - Servicios:
        - Immich:
            icon: immich.png
            href: https://immich.tomasmerino.com

        - Plex:
            icon: plex.png
            href: http://192.168.100.156:32400/web

        - Linkding:
            icon: linkding.png
            href: https://linkding.tomasmerino.com

        - LubeLogger:
            icon: lubelogger.png
            href: https://garage.tomasmerino.com
        
        - Grafana:
            icon: grafana.png
            href: https://grafana.tomasmerino.com

        - n8n:
            icon: n8n.png
            href: https://n8n.tomasmerino.com


    - Networking:
        - Router:
            icon: mdi-router-network-wireless
            href: http://192.168.100.1/

        - Pi-Hole (NAS):
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/pi-hole.png
            href: http://192.168.100.77/admin/login

        - Adguard Home (k8s):
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/adguard-home.png
            href: https://adguard.tomasmerino.com

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _self
  docker.yaml: ""
