apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - route.yaml

  - postgres/pvc.yaml
  - postgres/configMap.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/sealed-secret.yaml
