---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkding
  namespace: linkding
spec:
  encryptedData:
    LD_SUPERUSER_NAME: AgDc6D0cYQpJzh//eLXeS7b5ErZR8e/WEb0TDGkiFZw9P2DvIh99PkEkVUsNUt6YMDOToquTJytrS399Xo/oa8GV1Ltg0r/+RY0DlZ0qMxiTeaE2Jbxfo9JvcNcXA+HQalMxcPeYy4+iW2vGHUOFzZ0fiDutI9EAFM7GpRSjs3J3p4E1Flvw16TQfz2sIiNUb6gEmGvy458DKy8Ch24KMHjlYjb+w1wEY+kwG+vMS6kthIo4N9j0poNyMUnq3xYm4C6GPJ/gCe/BpSv3T3SVydvIU9QvSBQh67/UGJd7OtdMqgNHbYGDd2+qU76MygoSquTmpkNaGi4TjSHqYMPvFSdcl6WMfe9MvvgVKpxj2to0nDMWK784564fN2mjLlZhl+qpYhwWAlf7ZQDfWSqwths3CTEgitDc0sYFauZxm6Gkf2PtIjoBjGCo6r4Gprioiix/OiPBewbbbJfM8ffcsuXw9rkLEsVD6+7r1PduevUdehfSPAmqMY2iY59mdvPq/2zgSXX00EfLqmRN0aAhn4JVyXVoYbJZfDtVLqUuiMb19TTZ4dOijuvpFhoG6IrVRV1rWj0BUDkhxAace5sb8BoL6RPRo1dhvPLRa9zZ/mLCHVRQsQ0aGyzRvkt7ze8MvxKhxQi92dRk1b9BaaI4c1KYiqU4RzbnYHaECIv/9J0+UmI6J/GheAlZemTaHPdXxVJL2JwwpA==
    LD_SUPERUSER_PASSWORD: AgAm9cCfkwtVLW6JYmcdhAb1jxXe+rZ3VnC1GiegSJ/kareE7yZaOj1ObYi71xxLpPPDTXvjurz3J17SAa1GtTB0FcF1WHHKtvcNTzDuewgqK+TT5yFa2gQZ/0yzRQNdfUeY6DNZYA0Ef/p6zv9XLSDfBYsBTLWHOytRCi4W7VDkG5RTwk8KjUnNpZJR03ht1lMaeTHe7FMHYJS5+Yx0k92xlzAo6S75dQJSN1LTTWRAblQSTc52K68uhR9bMC1P1CG36lE4oKA9PTPNCggjIkeyzXn6inAUtUUPEH+pa5H9ahtEukseSCmDcLrTqa2iXxUWbDlCq8GdLB1his5PR7C5zxeIMhk5PLqXnMxUGCemEn5F8XYuu1PG9TWvis3nMqweY1jdMK9C0MKQK68LBqHqVzih1viGjAbmo7/XeGGtuyu6JbauarHcTKxcKc6sVqXJoGZQRhPq7QPRiGo3SFA81rJfQ/XCm2iuoXA677y7sLJJbUHTamJk4XnWbW9wLcQIYFqwlvWLixtjtVV8w2M/Tb3Y43qOFwGvlG4vNoz6NX2+4mKIibkDwPo1PGVvBxKKqVQVKuFsTmk3HPIPBSacruVBppLqUOIqrbaCmvf7Rs9fWEJWCVvIqcD40S5/TQoBg3X4lEiK/azsO1FY1H1XgL+gpfY48Ri+sWOb/ITH8QedtsIOW1Z4pHwjjnQzHJvdRChj9/mvKfLL
  template:
    metadata:
      name: linkding
      namespace: linkding
    type: Opaque
