---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgBS9jb6/Kn2Iubng/TE3vX+oQjS9F1gdFA9IFEDV3VXRl/xfNHgjNFNoLmZhmuoov0nH+zHLBZbi444eu1gioqTtj7KTosoJfpC6VUhHawmQX8YP+UYmsLDbNSYbUmiAR4vUPo1ONY+dNj+b43xl+K4RWscHZKXwmxrhb3ALEjAGNGUV+DBT5tRgH53xQCtsdcqGy1qWved2LrBJQMdYOBh35pajbLLb7ucraw7EDxAtqNIpaWmE3YtaqtNomsTOb4qHdS+ZmrVE8gsFzIG9utIUviQiV8gKHWVWgZ+sKAhnjNpC9B3ZXmbc3bFC+EFc9qjCixG1toB4EdJ8QSZNvgBWfVpOyDyTKHi0EjpNgoP86dwUGVARy7mt9NgA6+UhmfgXkA7P+ChmbASuP90AjJjlMVgBcBvR0kKAPIobmsLD8lMvXJYERMHHEQsoE+yDYVdbh8BSCRb9lkQEeelzgdFTyxbaMnrhuNMJFhd9PN5RUVNjF28ehKla6UQrCRYGOQoHNYkvHgT5vcXUARlCIElpN0ZCOdk7TjNC6WDop5R+GiKbUgm79M/1ZgBUOuWOk6ftK2LN85eVKE3EVdTAq3d6LIRYW/cPLczuKHyJk6KjzzuwuIvrjXY3s3CuECTCFIzyksg/Y2SvUxuBxVlayQQH8dkYaWAx3cuBpPyxikOR7TUwrVvbwry08gmujZzR/cq1CsVopNlnuMTgZP4yRLc2D1P3tnl+vUJljvM1ql2EAUe8SclM/s7uXRLM8uX638GVMsMY6XXpd991ToN
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
