apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitmagnet-config
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 1Gi
