---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitmagnet
  namespace: torrent
spec:
  encryptedData:
    PGUSER: AgAwvYq95NIneFQHAID3uDflqnA8ng+GJvuD+Cte3T12AyHJTPWKVxq1usf6iCuu79M2q07+7lKEOChlKJcHIlIQT+WzU2aVKg6DVTi/pR+W+WAI3YJbEpv9ecL5xEJ9WC2gTU/fUFCuo02m/7ImyJhlyjxXVbdhsEi4nxpKJfkXt4tLakyYlRao3wp7GvqKRZZu35UVWRK0LF71w2P93F+3GoMC5/UWLN7jbUhkKw+/jBEhMwGKC6PlQeNQaeXrvTurfC2CGGoNgBc0Vh9luqe6dX/mLE/LOfXjzD0uh4xt6NPJeyyo/bVVHmYCQ8R9dHDum9aoVm8duZh8gFzTXKmIIgSEMZiEAkkQNTkBwJOTY+A+2rHJuic5On+uWBCQP6j5hogeyFLcHQvoC0XB6QRG/mp8msF1tnA3YKE//YrMuvd5I3Xn4ykd6zv1N5XOThpMSkdrwg4FYMxGvLyD0m+isn/2JECOEp5BbZ7UIQ5SGNxjVX+k1kpzjCNSieX3jhLObI0PIe6lXIdP6SSn0foA5RCW8jgfmg69qAko0IVqXnxpp4T97FxFGqfJRgrTBxHfFdEzoOihtFhkf1gothsDDTgEbzTs+MLDqYMMUZGFReJhiruCdOQDBSpzYzUQ7+SCP8wsi++GiIWKpOj4+MjcBkrTQkUn9uVwXo9kdjGY3Gtpnjep5S6sdMhN/FA7lJDfaSGo5rDa+w==
    POSTGRES_PASSWORD: AgBvID9TKwajCtFMuHPr4r1Z5yQfAwqOPcEOrlES6AimyzMoisXhFJyKVjDV1cnXoIAaVLm1tqeegm3Cr9/9omRH00xLER1UD2nt3lTuPN4h+IaL16+XTGEXuPc6BKXA/J92nFXpGWiunM7OPS/5jrHN/O4MZuTHNZlIVFkbALUk4tOvJn2oyY9cfT5Qji0EWTNJmAQUA1S4u8z4hMXUGTARH5HzUORuS3OGnMfMNBfaLOVj+sPnu1Adzk1qECVaqz5BNepEtQ3C/ERGYP3l5iX793i/75pkIEOuJyNAcO/rJJ3aTU3AOYOTElJyz9c84rRk0nkvHfzESxTf6c9DdaNR+UBohOlK/ZoXzUweK0jAodGDQzZfCLAZNed1lrMER6S7BH+KdetFljcNjqGR0ZHAwYELh9a83EFFxR47L26vLbBcDej7wCb4zYZERRtIp1+pZrdWpjXP6oobSlu6L0B5Y15HlP61LpY4mdRFHh+JtBI6fzfmrZUBtmxwCQlZqdVvrraJaOP0UB0LLFrXsrIF6Li2ng6xJUUONrVDqccijimZuP9NKi9lE9GZ9ajmGziyCUznGvfJ9WlF8QlAR61BCwZ9T2hL3YbD4/V6b6QwXYFsmiuBAnze6pVMb0ojSRSGcGQWbjyP9Ji6yZZAIF11y1f9hKue+/QEYodTpg0qtFTNNKFmkoS0RuhjJB5/5fc+66mTEcIHwi8M
  template:
    metadata:
      name: bitmagnet
      namespace: torrent
    type: Opaque
