apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/deployment.yaml
  - backend/pvc.yaml
  - backend/service.yaml

  - database/statefulSet.yaml
  - database/pvc.yaml
  - database/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/configMap.yaml
  - frontend/route.yaml

  - sealed-secret.yaml
