apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/deployment.yaml
  - app/pvc.yaml
  - app/service.yaml
  - app/route.yaml

  - database/statefulSet.yaml
  - database/pvc.yaml
  - database/service.yaml

  - sealed-secret.yaml
