apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: job-ops
  namespace: job-op
spec:
  hostnames:
    - job-ops.tomasmerino.com
  parentRefs:
    - name: homelab-gateway
      namespace: networking
  rules:
    - backendRefs:
        - name: job-ops
          port: 3001
