apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 20Gi
