apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: media
  labels:
    app: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:release@sha256:5fee7f3e052c3d32d4edecafad68317394daae26f57d895fbd487886083725a7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: IMMICH_PORT
              value: "3003"
