apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booklore
  namespace: argocd
  annotations:
    infra.tomasmerino.com/status: "disabled"
    infra.tomasmerino.com/reason: "Replaced with grimmory as project died"
spec:
  project: default
  source:
    repoURL: https://github.com/Tuqui77/Homelab.git
    targetRevision: Main
    path: apps/booklore
  destination:
    server: https://kubernetes.default.svc
    namespace: books
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
