---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBSVoDqMv/LlMSF4smgqbHm6Wq12LinNQzvzyDJDZVsU59Y85eQXjs/FDtXGLgtAuyTtMb34f2O/Fw8a+w5CWYN1SVS8qSPjedh1ApUHs2B/q0pabYyP0d2zXxG4az8q9cUp9t9f6gHjaFcCT5h68KszUQuH1+WPMsI/yY7ZwBw/GPGAQH+Sh1tmDwaOFXDAKUZ9zhsq3Z9R97iYsaXEBtOrA+9JBFNNPMnYAyj6es0APeW9n+ino8X+LVnSw2FQR98pw4a95b7+SqZqXUEExDh+UtokmlTcrI0Lzz4iWwNJXlpYNqgDxFxDtO+6S4xp7/MM3xPxqivCwSAIbiZc8+gU71MaRJIcSAElWd6VwSrcbShW0vRvKFz0FHOzm/QY5Ng68M5GnVVxqP8e2y5QicRY8JpwPHJYRpzY0PD8yyoUuq2Hl9vlklIrL4YaEjXisSn7FmE+DZTlGkj0DQ8ZRsvABlyfuaqR/JXvawv5lHavtza1oucK5Mb4Z0PLA+SX+ZookuYaPEH+Ta2rgjovQET76BWu5jgfXSp10YvysS8T31JblElWnMBVNHceLN5O1DVsAHT6t5wp6hssrW/lL8YvWbZ45+LJPX6Eo9zfvRno6HC/3ii6lI7jN7i/BapdrYux4t+0USlVRUJM2S1YgZIutrdCTByT0NKs5xnHnAZoEr3mEC+pnlxDp/fR4zLJ2/WLY96djUC0aFCbF0DJIKX9g==
    client_secret: AgAnsEJsxtPbrrw4CUfhk2TKygXfvPYB+lD0ixp2SxNq5Yuvri7Cys1m8fIYfZHJkILoFLyHZTnllWPdEWcxzxOWqC/jGLEWyi1XFInxtHJRcwxjKA0uMTrC+JQhHF675qjq1Rc2aRjiCs8fLurbX084HEAQAC1uwfxOp9W7EoMpRzycCqJH9bY3piqpAxSqO08lzV9ERS3ZUncBY1b2iWAY7xm4gdOKJRo0vAoIeIVLp8/hcmutT72t2mpJy4UhIyT9oYljyLx/Knw8WlgF1+jAuN/FmniYmEsmUvjT5bB38YeeoY7Q7CtSOoSd7sOOwWq/81NqT0WnSLryjYF5P6aUIO7Xd1C4Vvya0bkVbfex2X4TSlrXUsHZCsfWGWAh3EKAzhy0JKoG7DFsVAj0ZTum+xl77BtHsULffIRuobXxjVGJJGVJkzv+XZifebBESo5lkI3YzK1uLqkKAyaJIcwPYAlurKl1j5sk00vLVXEghsyr/FVvuYePI9yuDJCD/BawTHszBgKhD0TjfmuQ5h5KRaWgXxR7kI8+f0YotTQfLx/4MQXngGre5qGbrEx6CVGnwZC0ALHgEBwzixiy/CfxoyeLjQpMgWvPiLT1VsVfoq8GkP2KlNxpGjXBkhK31a4GIQqkWyR0iSBBYJtIDnCq4LHkEXNoBN449mlW+MkCo1yNPYHDxfV1nNirFY8c6qIftiLVBTcQSnAUVSsNTUn5UKfa7eKpC2gP8aoWeT+7puQ5t5T9CKXxjXCmn1dW23mLMxY1scxBokFdOU0VrfgF
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
