apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controller/deployment.yaml
  - controller/rbac.yaml

  - dashboard/deployment.yaml
  - dashboard/rbac.yaml
  - dashboard/service.yaml
