apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinephage
  namespace: media
  labels:
    app: cinephage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinephage
  template:
    metadata:
      labels:
        app: cinephage
    spec:
      containers:
        - name: cinephage
          image: ghcr.io/moldytaint/cinephage:dev@sha256:bfd37f61cde07019d09e97e66f43655fbb0efd6df8e5fb8c899eaac6a2d7dad6
          ports:
            - containerPort: 3000
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Argentina/Buenos_Aires
            - name: ORIGIN
              value: "https://cinephage.tomasmerino.com"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 2
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 60
            periodSeconds: 10
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
            - mountPath: /downloads/tm-downloads
              name: tm-downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: cinephage-config-test
        - name: media
          persistentVolumeClaim:
            claimName: plex-media
        - name: tm-downloads
          persistentVolumeClaim:
            claimName: transmission-downloads
