apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinephage
  namespace: media
  labels:
    app: cinephage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinephage
  template:
    metadata:
      labels:
        app: cinephage
    spec:
      containers:
        - name: cinephage
          image: ghcr.io/moldytaint/cinephage:dev@sha256:b8a8746acde4615f2062d5c77cfc6ed5d3313b697bdec993ff3ba5fc52eb593c
          ports:
            - containerPort: 3000
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Argentina/Buenos_Aires
            - name: ORIGIN
              value: "https://cinephage.tomasmerino.com"
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: cinephage
                  key: BETTER_AUTH_SECRET
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 90
            failureThreshold: 6
            periodSeconds: 10
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
            - mountPath: /downloads/tm-downloads
              name: tm-downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: cinephage-config
        - name: media
          persistentVolumeClaim:
            claimName: plex-media
        - name: tm-downloads
          persistentVolumeClaim:
            claimName: transmission-downloads
