apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinephage-config-test
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 10Gi
