---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cinephage
  namespace: media
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgCdSiAEhQ4Bbk2z3XZ7OUGn2DBVY4Um8Tclrg+n/GPsDPHmwUGfKYF/9t3juOOxouiL1EbQ/LxXyf84/M7Jcinpbpf4W6U02XmNP/F7lnYE4XZyNn6Ltv9VYe0e3qHs0kPUu7xI7gcClFWMDu4Br5Efxx7S8dZA1qPfRB1xpOAuTLt/Pcxu6lsjPAwxfLmxwCct42admILPyZmZXO/K45d0HvLnmNq9xzUqifLJzw0AyPSdhQTuyP95kWK6PjgmiiPqdiEOuIc/XCVxsVetiRl/eTkbXtzOsCZ5Au3a9b5YpJyPDF6y51GmEFmidNufMgorQrmbImgjnPwdWU9t/Hb+1X3XKrwki7gTGMILn4E/NCHAi7CQxAHk7xURAXLkD1r07jCvpCIlxK1yyu0oPYQCcXLRF/nZyGjjuf5kURpheTWaGeNs8DEkV/7wPJuLVXgTNRD9DPo19tEYpdtA/3Yql64KadNRqPmJ+iFyl+WhrLoAnyf+dFHy2MoIaTPPea56mhKemwniuLByfryBoNDtHcRLOQc5q/5vm5T3cpZx6kRkoHXQgiOuRw1iOeIy1hDXnz7h+hSiL+NdgqoGKpzsdy+4r0MDAZlLbP91MeKIwQoK6aHSMwVgJvO13mgbaICz2EC3oXwsVwme8o3PyWlNMuE++Zdso/sOd3EsJXvoY++ZFzL/a+XFflfSVpRVEyYHc/5pIs5GUwm7skudN+bnTHAGhI45MdvFcHLBRRGXHQ==
  template:
    metadata:
      name: cinephage
      namespace: media
    type: Opaque
