---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cinephage
  namespace: media
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgDBDYOjzJe/Pxs5pgtaLzSNJSYL8kysqt7PGY3a+dnihQU7dIH+2Y6jFf1n7y/vmO3tQxYGKEWFQ9/5FOHY3454qzQmJF902whdqowQzbs5y16yy6Cc2JWvx7qyswcJUxwX8NGDdl4heBfWiqCiFO55TEXtVuvF8rrBDHYGoY+LxK4qkLiMAeaOdTTUluqpPX0humnmiKD7GTpskYwsRV4oPjf2mTlmxfSnsaZ6j1NmtAC/louOmWWATpodPCKHBCHG9qFRvqGKOVioVL/yjdSyveuBihef9y+NymS5+X3wfkv6BRDt96VDB3X0sRKa4DAYPEKKQRsRVMpxWig7IztsBUqXfKpWL1JSukTYcm5JHwbn1DDx4OfVjIVMgZ4PBA6cekziG10RkTWzXECzSgHeSRDcSwFpJacy65bmwvafZ+PdaP7hzNlb0FXln8Z0Hq7EsWeKUGi56StQEuf24fnXGtGORYo+t3jlr+Sm4lMjS7xjoKvfXFO35yM7k97y3pgGwdD3gAIIdtcRHbTp3pZyqjVNvXFoI7uoiUPftPzlCr6xjKG4VVW0zUKXeOnBPkxvyiB3qcs0ECzUAcFgr6KGVcUAtpxlhflAOrYeP2Bgm8UpsDuUR/FL/s8FgfRT0HbaWUhyTXDLQznZaaHury9+vj/6nfdBBzr87pF+NL3fujvAJQelQETXT0nOjglFaREc9dk3NtCrmX4j/rt8zd5n5UD5SrYKPlw9qXJztOulZLmpUJIlsY9ukaKVgw==
  template:
    metadata:
      name: cinephage
      namespace: media
    type: Opaque
