apiVersion: apps/v1
kind: Deployment
metadata:
  name: grimmory
  namespace: books
  labels:
    app: grimmory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grimmory
  template:
    metadata:
      labels:
        app: grimmory
    spec:
      containers:
        - name: grimmory
          image: ghcr.io/grimmory-tools/grimmory:v3.2.0
          ports:
            - containerPort: 6060
          env:
            - name: BOOKLORE_PORT
              value: "6060"
            - name: TZ
              value: America/Argentina/Buenos_Aires
            - name: DATABASE_URL
              value: jdbc:mariadb://mariadb:3306/grimmory
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grimmory
                  key: DB_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grimmory
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /books
              name: books
            - mountPath: /bookdrop
              name: bookdrop
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grimmory-data
        - name: books
          persistentVolumeClaim:
            claimName: books
        - name: bookdrop
          persistentVolumeClaim:
            claimName: grimmory-bookdrop
