apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 100Gi
