apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinephage-dev-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 2Gi
