apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cinephage-dev
  namespace: media
spec:
  hostnames:
    - cinephage-dev.tomasmerino.com
  parentRefs:
    - name: homelab-gateway
      namespace: networking
  rules:
    - backendRefs:
        - name: cinephage-dev
          port: 3000
