apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinephage
  namespace: media
  labels:
    app: cinephage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinephage
  template:
    metadata:
      labels:
        app: cinephage
    spec:
      containers:
        - name: cinephage
          image: ghcr.io/moldytaint/cinephage:latest@sha256:0426c193fc71e495785d9c339d601260d29959e5abb7885fbefd64af1c6ce1be
          ports:
            - containerPort: 3000
          env:
            - name: TZ
              value: America/Argentina/Buenos_Aires
            - name: ORIGIN
              value: "https://cinephage.tomasmerino.com"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
            - mountPath: /qb-downloads
              name: qb-downloads
            - mountPath: /tm-downloads
              name: tm-downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: cinephage-config
        - name: media
          persistentVolumeClaim:
            claimName: plex-media
        - name: qb-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
        - name: tm-downloads
          persistentVolumeClaim:
            claimName: transmission-downloads
