apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - stable/deployment.yaml
  - stable/pvc.yaml
  - stable/route.yaml
  - stable/service.yaml

  # resources for dev testing:
  - dev/deployment.yaml
  - dev/pvc.yaml
  - dev/route.yaml
  - dev/service.yaml
