apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 100Gi
