apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: torrent
spec:
  storageClassName: nfs-homelab
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
