---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_SECRET_KEY: AgAc90+/NBXQjFoWCsz4+hRNXPZ/2jRT8mWexYHoIosYDgy5It7e58NzFFYsI4DefW9Kq/1VykUqRJQMOomLCL/yVoIdy/fPYO2i4vgO41nkNoAKF1nM+kBpzUe/yGVuaSiC2nWI3B2aIDPKpqLYuK79PdqcW/jnfo5NxSsfsNJDJ2ckfGOcxwa3tOCxBtwI9Vx1aKTg8g0WV/yUIuoTBgYv7CBZBut7e9+KhqxPLqApGHJXF+zyR/I+R4ktyeAcG74/3A5MNaipxvxhX/8KS+/xrLQZ2xwd9Pup9lZ8dkiIGW1svmUk1wqBGcrbwutBmywC2C51NXXoghlyt2KmuaBxZDVyMKbIJbcQm9eOx/EzUVL+dv/TPJ3E47zRBkBN0vu+qwtaXRbKQRZIiCEYY2/ZSITgb0u6Gocpn+yetEJMo4AS4XjpkX2/qbg1z6+yRlVY/LTo2IksWfXnSBj95tqk3qPeBilJgKxSr562yP6h8MNT4RkJCY4vsruz95DEfDYNUjMkxROxtGbgwQXBWc8+nRlYUYy3MSsSp5YULy1EAPnwhdSX1FKFBB5SysL/KL7tKke9X2zAP06Pytc78R7vBkkSNxysbWim8sjD/vQTcqjkGtibGo2z4uN0IHaTB9gsGsyUrJEl9CO7SRffz5UynNweOe2ReQjZPxSUvCnF/YMIiq+g4X/qKrQ7u1oXXq8X5KCF+cnoPtyqg9OQBfNevDnbcBLxdPP7nEDk0Nf5zYoBR28/o3T2Cq0jT2qnnZ32bk2p4yXGR7cbnqIdT482xhKK0d9zbrfi6CcdQTnVhPWBM+SKfw==
  template:
    metadata:
      name: paperless
      namespace: paperless
    type: Opaque
