---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: robusta-credentials
  namespace: monitoring
spec:
  encryptedData:
    ACCOUNT_ID: AgCJqzyXlVt6zqcExhskz9UUyuWM4R7AwvDHucsgP+JcoMjrf5eCM02E4zmFRfSiipxwLAx4o1LYHvDcmWQJxhx/6JIpPX0L8vl5ChS0ts6xYcDS+AchQ+/Xu8RGq4ZAdGLzMMWIZBH0+iCcBSAbWksot3zCzxaRlPw3SzgsShmrQLSW16NKUEn8FCcDwt6u846Kbcek8syiGcc/s+GmXK5AmX7yLoj5cgeA6aktQ7BcH0hga88aaA0N+m8gzyZ0hCi3fhGekV9a0ZawZBjR9xwes2tgjRO7CXRLaz+ADdjdJ0b9Vy7dedLhP+e2doLuebHwIn9rPVwsI1v77KhDZITbLqviWvYIhprhfvx7U6LHFnj4IX1C4XSty2GBgwlxPo0tIlWWtXpwTrZ3B4OhqZCj2LzhJD0bWyQXkyh8gNzUqZXfVhaxwYu3JsvtWt6lJGbY9l8S+aGfNmwEyP+bGqvFjyuJ5e1luh12SQkd2EjNC/1Q4GmpgyUdgr3UxorIZUdkxOz083EFqr0bwKR2kqbfYDn55zhneAssBVBao5h/su7ZWlWJNdJjQmhkV/vc51p4uCuw1L6A8aBSXlPCbbIC692doRzZ8SVU4ewGkrXYwthDL8PhQ0Is0woAro52Dmt0w7VAIf00ZtLfNVBFUd3Q8K0QpI0FcUY2AyKMYACIz0zX27JtURvj9ZlDFlAmOd7c666dzMiuMZKks0v9H66YYAFu8qQBypJ+ea0Gg6l6mTX04a0=
    SIGNING_KEY: AgBbnxSuBeSPz6XtIA5HEXlYMjC/YPPy/NVKZ6r8saDTngB0czo0JVhPaKbH0GCqHYMeoNq/pboPMMtv7t+9QQH59bnDXacmjHgUxqhmSE+iDXS0J+ltlFq8DmRO+FHP+6r35/rJoQbQiKRg0HBnP7QE+Kvzi5pUGxQoPzDlPW62BqHjRfT4yvuANjKe7uqPJ6VzxaheZebRJ3b8a7NI92/Ysblkj5EDd5+CiBzF9iVleU2NcUSGYIMmGRD0AItftOOZ5hZ7qe/sq9RkjFr3KYIwJ7qlT3vT8W1Y4iahhuI9eLDrgtlwkhc5EbJtwb9V5KSZ6W82LumcbmhdIGnMyNY3gwn2vWeoP85pB0jjLwBoSf7h+zwygTUp534GOtP6/mNg68xrhuMG6aEVR1ByumE+CO6BAetKAUkO1olJ4UBX5X+RDTcvAu7/ol5oiD2VaSOtd0a5nk8R1Q3bfpmFACq6y3hJAEBSxTC8y90eY1QPdRx7CEr+ZhXY54x2HaiUCPiotgLaq8/coheLvI5cu9PjqeIO8UV5+vTEjrGLRslm4AoIDB5ntQN8++ryTMNxyMWVtxlTGvCXlk3USE5SSnKg5i5ZZfbquBOw1+x3zmAKEGjr0D2CEw1pTd9rOdRzwloGk0gXmMoLgZVoloOBOm1h6OL8vYGJ+J7vTf+dxbLBlGwfobn9ym2yUem7g7rigEzFfHG3+wFnIrtWfaA9pWSlNSJUNyOPeOMDdaA2srN6rpZ0Yqs=
  template:
    metadata:
      name: robusta-credentials
      namespace: monitoring
    type: Opaque
