---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: robusta-secrets
  namespace: monitoring
spec:
  encryptedData:
    ROBUSTA_UI_TOKEN: AgCP2Mi32LAbEag7hEQx+EumwPEqHJnTiHs4khrYCUc+rRG2MghgS79W3/57TCw7AejpCnthrqBmHKFyZsXAuLzGBn3mWQz6CwtAazNSHdggfPFE0SiuQ0PKA8mkKUBcfyDysWg4DqAQTTju3SsK078TiDTm9VaHkB4TA8PBlHZOE5rGDCnh2O2CCkjFSl2TppgV8AzFXDQBQSqCcvW80rof/okjghVr/KEi/iHJD8vnO9KlDK5UHtEverHm/1JGucunTHzrjAGD6VQn8Fe4ufM/kK9kWvDguAIbdkdMV/x8O9Rb4+pfVQ3pL2XKijWdYS1QLWzQKySE/gX2vRMT95JPprCeYogyWp7l0N+hm/YRAd9lRHLzbbDmuuWUaDCbM8F0KTuLK7oj7Ceoab4xsVOkx1oVlX2g0getkqzoeORFqqumhQS7bhIBZWjc2U922dcOZnfjkDtD+Zoymm2TFcPt8U1MfR1XeMSKTC+Ji7LqdNnTXwgrVlvkYqChbmQwCTxZ4jPyApOinF6LajmaOGc4EFwwGuGqvkbm7E5jfoav04oSGmZ4L7fA5VbqVBEx7tgxj/po/GIScMT5lpOLAjh7T8X8nE7hVwsSfCqDf4XsJBOEjVHX+G5DzORE1FNofmowc70NRtQmiHQsdZY4BqyCtuCC4/q21yPU1u6GUuDoXVJrXbj+3A+Su49ye0foHeY3otQYEw0IgAm9uwx4Ikr16xZZl0HFCRujcb4yg/dfOWDNvHbXJsWQKJ9PSSLZbNdWCudf3TJb/R32ISd6Krk3TunAkoyoXw58Fvy+1Ft8bE7N7ClD5jlqZwl33DND/ZJRD36g09PzkKqfaQdmxrGNhDP37Q+Zt968GnWX173DnoJdiRM6N/zPNsIu6MlXbxL8NjKAL0t6GN3R29uCrbp34oPFD+0MZ+HSqykAXKBqPFFTKKr7XrdNhPb9L9/J8SP5TTbqcnX6FiBVkwRqO9DJVhb7cdFQe9kOk0LAEUWc1Wy8+Jtyhv6JiePmVzUssiuJTCWhaX6FvnmZBxqlj7yaIwwFilTuANnN2evQKkxmbzkPftj+vHDS5rVn85pB2ieyDoIjuvooUtW5T/PebrayEgDvV/Ih6vApwUagd5rY/c+ls0aGD+EN6/AboKFYP+56pTEkQ8E1ystHvV6+bBFky5JdfHPJJMxnvmpKm/2uq4KAw8OQj29axiVNNKHZvyqIwvLLg/IPFgH+wi5bbg31WYaIYRx0Ca7xuYxCWOV+y/l/2bvj3gOZjKokZJSJodTe7XC2xSG/hOFXFu9eIJ0hXTzC8wKPGbjEZqIzrIZq/iERYJFC0Yg0zSLtxg==
  template:
    metadata:
      name: robusta-secrets
      namespace: monitoring
    type: Opaque
