apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
          ports:
            - containerPort: 2283
              name: http
          env:
            - name: UPLOAD_LOCATION
              value: /usr/src/app/upload
            - name: LIBRARY_LOCATION
              value: /usr/src/app/library
            - name: IMMICH_PORT
              value: "2283"
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_HOSTNAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: DB_DATABASE_NAME
            - name: REDIS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db
                  key: REDIS_HOSTNAME
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: uploads
            - mountPath: /usr/src/app/library
              name: library
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: immich-uploads
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
