apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-books
  namespace: books
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 20Gi
