apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 10Gi
