apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          env:
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ALLOWED_NETWORKS
              value: "192.168.100.0/24,10.244.0.0/16"
          ports:
            - containerPort: 32400
          resources:
            requests:
              cpu: 25m
              memory: 250Mi
            limits:
              cpu: 25m
              memory: 250Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          persistentVolumeClaim:
            claimName: plex-media
