apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01
      containers:
        - name: plex
          image: plexinc/pms-docker:1.43.0.10492-121068a07
          env:
            - name: ADVERTISE_IP
              value: "http://192.168.100.156:32400/"
            - name: ALLOWED_NETWORKS
              value: "192.168.100.0/24,10.244.0.0/16"
          ports:
            - containerPort: 32400
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          persistentVolumeClaim:
            claimName: plex-media
