---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCKMibrOFmR+ZLIHt0XtnxvZpBmS+gIg2TH/iPVDOnbw9YtP3S69wsT60h5tiUeUe1XQ3PWCMyWCzy5udcMMZcX09NC4061Vf++MNiR+k3kaZh6C9QndEfNzeBy7fHjTDLGCqhRHjnGrwiTylZ1x59saNQHkv2YXDoNZu44RrAR0f387vjmHlP/yBdXyoUGMxXlerEGSzuiwQnHDha9zPisW4Rwei1x/PYzEPApoAiakX7fA/8e00kjCtpAXo6lQq0Zy06ewoth0+qFqCSRc1nWh5VcOzfZbNeHN1Kxw8GsaW2ig6c5OuqRjmyeNGL1K8oxssipJAFReJfeB9hoP6+l/4UvPjuQ6DngYIH6edvaVyhlA93tBqjzFwxjoQPJ4NRtRjp/1l1jKPNYxZkS4iZXBE3HaGzV+S1kfUuF/td6GGqk6FeV/Sy3rV5MCdKNzbcfuI4CY8vWDT51Ei7WRbWD3SWTU+R+w+EcNHKp4c5csKNrX0hkqYUNwDE+VfAC7vaS4RuTQt/IhLRGFmqqWeu8URaxBbYi/JA9EmPINCcbheToxloYJS39knNXritYcqTN7lnnlaR8QjscG9s8JJqmFJysthN7SHJ4a/zhOAVOypdo3FkfHMet2dnkEpfmcqvI+3qWVxe/9fUYLdPMIfTUUqwSQfXIjoodtQRD2GbIeFeHKQ4/hTx1WBNlmwJ2CPtRQ4JqmdQG7WCgcGN4OV4a5197wSnb1rZaNzl+jYIMcvs/wm5uLPgt
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
