apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger
  namespace: lubelogger
spec:
  accessModes:
    - readWriteOnce
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 5Gi
