apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces
  - referenceGrants/ns-argocd.yaml
  - referenceGrants/ns-media.yaml
  - storage
  - networking
  - sealed-secrets
  - cert-manager
  - crds
  - monitoring
