apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tomasmerino
  namespace: networking
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.tomasmerino.com"
    - "tomasmerino.com"
    
