apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.4.0
    helm:
      values: |
        configs:
          cm:
            url: https://argocd.tomasmerino.com
            server.insecure: true


          server:
            extraArgs:
              - --insecure
            service:
              type: ClusterIP
              servicePortHttp: 80

          crds:
            install: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
