apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kavita
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tuqui77/Homelab.git
    targetRevision: Main
    path: apps/kavita
  destination:
    server: https://kubernetes.default.svc
    namespace: books
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
