apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: books
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-homelab
  resources:
    requests:
      storage: 2Gi
