name: AI-powered PR Description Generator

on:
  pull_request:
    branches: [Main]


jobs:
  generate-pr-description:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: AI-Powered PR Description Generator
        uses: 57blocks/ai-powered-pr-description-generator@1.1.0
        with:
          ai_name: 'gemini'
          model_name: 'gemini-1.5-flash-latest'
          api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_jira: false
