name: Validate GitOps Manifests

on:
  pull_request:
    branches:
      - Main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Instalamos herramientas necesarias
      - name: Setup Tools
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          wget https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Infrastructure Sub-directories
        run: |
          # Buscamos recursivamente todos los directorios que tengan un kustomization.yaml
          find infrastructure -type f -name "kustomization.yaml" -exec dirname {} \; | while read dir; do
            echo "--- Validating Infrastructure: $dir ---"
            kustomize build "$dir" | kubeconform -summary -strict -ignore-missing-schemas
          done

      - name: Validate Apps Sub-directories
        run: |
          find apps -type f -name "kustomization.yaml" -exec dirname {} \; | while read dir; do
            echo "--- Validating App: $dir ---"
            kustomize build "$dir" | kubeconform -summary -strict -ignore-missing-schemas
          done
