
name: Validate Kubernetes Manifests

on:
  pull_request:
    branches: [Main]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: yokawasa/action-setup-kube-tools@v0.13.1
        with:
          setup-tools: |
              kubeconform
              kustomize
          kubeconform: 0.5.0
          kustomize: 4.5.7
      - run: |
          kustomize build apps | kubeconform -strict -summary -verbose \
            -skip CustomResourceDefinition \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
          kustomize build infrastructure | kubeconform -strict -summary -verbose \
            -skip CustomResourceDefinition \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'


  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          pip install yamllint
          yamllint -d relaxed apps/ infrastructure/

