apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install.yaml
  - route.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    path: patch-argocd-cm.yaml

  - target:
      kind: Deployment
      name: argocd-server
      namespace: argocd
    path: patch-argocd-server.yaml
